// Згенеровано scripts/gen-routes.ts — не редагувати вручну.
export const routes = {
  me: {
    get: { method: "GET", path: "/v1/me" },
    update: { method: "PATCH", path: "/v1/me" },
    delete: { method: "DELETE", path: "/v1/me" },
    badges: { method: "GET", path: "/v1/me/badges" },
    sessions: { method: "GET", path: "/v1/me/sessions" },
    stats: { method: "GET", path: "/v1/me/stats" },
    revokeSession: { method: "DELETE", path: "/v1/me/sessions/:id" },
  },
  tracks: {
    browse: { method: "GET", path: "/v1/tracks" },
    get: { method: "GET", path: "/v1/tracks/:id" },
    lyrics: { method: "GET", path: "/v1/tracks/:id/lyrics" },
    playback: { method: "GET", path: "/v1/tracks/:id/playback" },
    radio: { method: "GET", path: "/v1/tracks/:id/radio" },
  },
  artists: {
    list: { method: "GET", path: "/v1/artists" },
    get: { method: "GET", path: "/v1/artists/:id" },
    tracks: { method: "GET", path: "/v1/artists/:id/tracks" },
  },
  releases: {
    get: { method: "GET", path: "/v1/releases/:id" },
    newReleases: { method: "GET", path: "/v1/releases" },
  },
  genres: {
    list: { method: "GET", path: "/v1/genres" },
    get: { method: "GET", path: "/v1/genres/:id" },
  },
  discover: {
    home: { method: "GET", path: "/v1/home" },
    charts: { method: "GET", path: "/v1/charts/top" },
    timeline: { method: "GET", path: "/v1/time-machine" },
    era: { method: "GET", path: "/v1/time-machine/:from/:to" },
    stats: { method: "GET", path: "/v1/stats/catalog" },
    search: { method: "GET", path: "/v1/search" },
    recommendations: { method: "GET", path: "/v1/me/recommendations" },
    taste: { method: "GET", path: "/v1/me/taste" },
  },
  library: {
    overview: { method: "GET", path: "/v1/me/library" },
    likedTracks: { method: "GET", path: "/v1/me/tracks" },
    likedIds: { method: "GET", path: "/v1/me/tracks/ids" },
    likeTrack: { method: "PUT", path: "/v1/me/tracks/:id" },
    unlikeTrack: { method: "DELETE", path: "/v1/me/tracks/:id" },
    saveRelease: { method: "PUT", path: "/v1/me/releases/:id" },
    unsaveRelease: { method: "DELETE", path: "/v1/me/releases/:id" },
    followArtist: { method: "PUT", path: "/v1/me/following/artists/:id" },
    unfollowArtist: { method: "DELETE", path: "/v1/me/following/artists/:id" },
    history: { method: "GET", path: "/v1/me/history" },
    clearHistory: { method: "DELETE", path: "/v1/me/history" },
    reportPlay: { method: "POST", path: "/v1/plays" },
  },
  playlists: {
    create: { method: "POST", path: "/v1/playlists" },
    browse: { method: "GET", path: "/v1/playlists" },
    get: { method: "GET", path: "/v1/playlists/:id" },
    update: { method: "PATCH", path: "/v1/playlists/:id" },
    delete: { method: "DELETE", path: "/v1/playlists/:id" },
    addItems: { method: "POST", path: "/v1/playlists/:id/items" },
    removeItem: { method: "DELETE", path: "/v1/playlists/:id/items/:itemId" },
    moveItem: { method: "PATCH", path: "/v1/playlists/:id/items/:itemId" },
    follow: { method: "PUT", path: "/v1/playlists/:id/follow" },
    unfollow: { method: "DELETE", path: "/v1/playlists/:id/follow" },
  },
  ratings: {
    list: { method: "GET", path: "/v1/tracks/:id/ratings" },
    put: { method: "PUT", path: "/v1/tracks/:id/rating" },
    delete: { method: "DELETE", path: "/v1/tracks/:id/rating" },
  },
  users: {
    get: { method: "GET", path: "/v1/users/:id" },
    common: { method: "GET", path: "/v1/users/:id/common" },
    playlists: { method: "GET", path: "/v1/users/:id/playlists" },
    followers: { method: "GET", path: "/v1/users/:id/followers" },
    following: { method: "GET", path: "/v1/users/:id/following" },
    follow: { method: "PUT", path: "/v1/users/:id/follow" },
    unfollow: { method: "DELETE", path: "/v1/users/:id/follow" },
    block: { method: "PUT", path: "/v1/users/:id/block" },
    unblock: { method: "DELETE", path: "/v1/users/:id/block" },
  },
  conversations: {
    list: { method: "GET", path: "/v1/conversations" },
    open: { method: "POST", path: "/v1/conversations" },
    get: { method: "GET", path: "/v1/conversations/:id" },
    messages: { method: "GET", path: "/v1/conversations/:id/messages" },
    send: { method: "POST", path: "/v1/conversations/:id/messages" },
    read: { method: "POST", path: "/v1/conversations/:id/read" },
    respond: { method: "POST", path: "/v1/conversations/:id/respond" },
    clear: { method: "POST", path: "/v1/conversations/:id/clear" },
    deleteMessage: { method: "DELETE", path: "/v1/messages/:id" },
  },
  threads: {
    list: { method: "GET", path: "/v1/threads" },
    create: { method: "POST", path: "/v1/threads" },
    get: { method: "GET", path: "/v1/threads/:id" },
    reply: { method: "POST", path: "/v1/threads/:id/posts" },
    subscribe: { method: "PUT", path: "/v1/threads/:id/subscription" },
    unsubscribe: { method: "DELETE", path: "/v1/threads/:id/subscription" },
    delete: { method: "DELETE", path: "/v1/threads/:id" },
    deletePost: { method: "DELETE", path: "/v1/posts/:id" },
  },
  notifications: {
    list: { method: "GET", path: "/v1/notifications" },
    markRead: { method: "POST", path: "/v1/notifications/read" },
  },
  uploads: {
    create: { method: "POST", path: "/v1/uploads" },
    complete: { method: "POST", path: "/v1/uploads/:id/complete" },
    status: { method: "GET", path: "/v1/uploads/:id" },
  },
  submissions: {
    create: { method: "POST", path: "/v1/submissions" },
    mine: { method: "GET", path: "/v1/me/submissions" },
    withdraw: { method: "DELETE", path: "/v1/submissions/:id" },
  },
  reports: {
    create: { method: "POST", path: "/v1/reports" },
    bug: { method: "POST", path: "/v1/bug-reports" },
  },
  admin: {
    stats: { method: "GET", path: "/v1/admin/stats" },
    submissions: { method: "GET", path: "/v1/admin/submissions" },
    review: { method: "POST", path: "/v1/admin/submissions/:id/review" },
    reports: { method: "GET", path: "/v1/admin/reports" },
    resolveReport: { method: "POST", path: "/v1/admin/reports/:id/resolve" },
    bugReports: { method: "GET", path: "/v1/admin/bug-reports" },
    setBugReportStatus: { method: "PATCH", path: "/v1/admin/bug-reports/:id" },
    tracks: { method: "GET", path: "/v1/admin/tracks" },
    track: { method: "GET", path: "/v1/admin/tracks/:id" },
    createTrack: { method: "POST", path: "/v1/admin/tracks" },
    updateTrack: { method: "PATCH", path: "/v1/admin/tracks/:id" },
    resolveTrackCheck: { method: "POST", path: "/v1/admin/tracks/:id/check" },
    deleteTrack: { method: "DELETE", path: "/v1/admin/tracks/:id" },
    updateArtist: { method: "PATCH", path: "/v1/admin/artists/:id" },
    users: { method: "GET", path: "/v1/admin/users" },
    setUser: { method: "PATCH", path: "/v1/admin/users/:id" },
    audit: { method: "GET", path: "/v1/admin/audit" },
  },
  premium: {
    plans: { method: "GET", path: "/v1/premium/plans" },
    subscription: { method: "GET", path: "/v1/me/subscription" },
    checkout: { method: "POST", path: "/v1/premium/checkout" },
    cancel: { method: "POST", path: "/v1/premium/cancel" },
    resume: { method: "POST", path: "/v1/premium/resume" },
  },
  legacy: {
    resolve: { method: "GET", path: "/v1/legacy/:kind/:id" },
  },
  battle: {
    recordWin: { method: "POST", path: "/v1/battle/wins" },
    wins: { method: "GET", path: "/v1/tracks/:id/battle-wins" },
  },
} as const;
